src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/config/SwaggerConfiguration.java, src/main/resources/application.yaml
N/A
whitelisting Payments app
```
[ ] Yes
[x] No
```
=> whitelist Payments app

.github/workflows/swagger.yml, audit.json
N/A
fix security scan
```
[ ] Yes
[x] No
```
=> fix Security scan

config/owasp/suppressions.xml
N/A
temporary suppression until upgrade to Spring Boot 2.4.x 
```
[ ] Yes
[x] No
```
=> temporary suppression until upgrade to Spring Boot 2.4.x 

build.gradle
N/A
elastic search api 7.11.2
```
[ ] Yes
[x] No
```
=> elastic search api 7.11.2

src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/scenarios/ReconcileCaseDataFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/testutils/data/CaseDataFixture.java
n/a
Fix for intermittent functional test failures on prod.
```
[ ] Yes
[x] No
```
=> functional test fix

src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/scenarios/ReconcileCaseDataFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsController.java, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsResponseControllerTest.java
N/A
distinct CCD ids
```
[ ] Yes
[x] No
```
=> distinct CCD ids

src/integrationTest/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsResponseIntegrationTest.java, src/integrationTest/resources/ccd-search-result-empty-surname-response.json, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchService.java
N/A
Surname returned as null in case of CCD data issue
```
[ ] Yes
[x] No
```
=> Surname returned as null in case of CCD data issue

src/main/resources/application.yaml
N/A
Application name change in spring conf
```
[ ] Yes
[x] No
```
=> Application name change in spring conf

Jenkinsfile_nightly, security.sh
N/A
fixing Nightly build security scan fix
```
[ ] Yes
[x] No
```
=> fixing Nightly build security scan fix

Jenkinsfile_nightly
N/A
enabling full functional tests in nightly build
```
[ ] Yes
[x] No
```
=> enabling full functional tests in nightly build

security.sh
N/A
create folder in nightly build
```
[ ] Yes
[x] No
```
=> create folder in nightly build

security.sh
N/A
access to new folder in security test report
```
[ ] Yes
[x] No
```
=> access to new folder in security test report

README.md, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchService.java, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchServiceTest.java
N/A
Update ReadMe and remove 100 limit on query
```
[ ] Yes
[x] No
```
=> Update ReadMe and remove 100 limit on query

src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsController.java, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsResponseControllerTest.java
N/A
empty list in supplementary details request
```
[ ] Yes
[x] No
```
=> empty list in supplementary details request

build.gradle, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchService.java, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchServiceTest.java
N/A
Add query record limit in CCD ES request
```
[ ] Yes
[x] No
```
=> Add query record limit in CCD ES request

build.gradle
N/A
fix CVE-2021-22145 in elasticsearch lib
```
[ ] Yes
[x] No
```
=> fix CVE in elasticsearch lib

charts/ia-case-access-api/Chart.yaml
N/A
Charts upgrade 3.6.0
```
[ ] Yes
[x] No
```
=> Charts upgrade 3.6.0

charts/ia-case-access-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```
=> RIA-5503: Upgrade base helm charts to latest

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, charts/ia-case-access-api/Chart.yaml, config/owasp/suppressions.xml
To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[X ] No
```
=> To upgrade java chart version

charts/ia-case-access-api/Chart.yaml
To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```
=> To revise chart version

build.gradle, config/owasp/suppressions.xml
RIA-7720
Upgrading libraries to fix suppressions
```
[ ] Yes
[x] No
```
=> RIA-7720 Solve vulnerabilities

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
https://tools.hmcts.net/jira/browse/RIA-6817
Adding fortify scan on jenkins nightly build
```
[ ] Yes
[x] No
```
=> RIA-6817 - add fortify scan on nightly builds

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-5679
Updating suppressions.
```
[ ] Yes
[X] No
```
=> RIA-5679 Updating suppressions

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-7386
Removed suppression of CVE-2023-41080, added dependency for it with specific version without vulnerability
```
[ ] Yes
[X] No
```
=> RIA-5679 Updating suppression to dependency

.github/renovate.json
=> DIAC-49 tuyrning renovate automerge off

.github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate config
=> DIAC-2 updating config options for renovate

Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/scenarios/ReconcileCaseDataFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/testutils/FunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/security/oauth2/IdamSystemTokenGenerator.java
https://tools.hmcts.net/jira/browse/DIAC-67
=> DIAC-67 fixing the non running functional tests

charts/ia-case-access-api/Chart.yaml
=> DIAC-000 upgraded java chart version

build.gradle
https://tools.hmcts.net/jira/browse/DIAC-2
Adding dependency to fix build
=> DIAC-002 adding dependency

Dockerfile, Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
https://tools.hmcts.net/jira/browse/DIAC-104
=> DIAC-104 turning on fortify

build.gradle
[DIAC-556](https://tools.hmcts.net/jira/browse/DIAC-556)
Remove deprecated JCenter
=> DIAC-556 Remove jcenter

src/integrationTest/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsResponseIntegrationTest.java, src/integrationTest/resources/ccd-search-result-empty-surname-response.json, src/integrationTest/resources/ccd-search-result-response.json, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/domain/entities/SupplementaryDetails.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/clients/model/ccd/CaseDetails.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsController.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/CcdSupplementaryDetailsSearchService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/controllers/SupplementaryDetailsResponseControllerTest.java
https://tools.hmcts.net/jira/browse/DIAC-616
Manage a Fee - Add appeal reference number
=> DIAC-616 Add case reference number to Supplementary details response

.github/workflows/delete-nightly-branch.yml, .github/workflows/pr-title-validation.yml, Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/testutils/data/IdamAuthProvider.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/domain/services/IdamService.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/config/CacheConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/security/oauth2/IdamSystemTokenGenerator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/security/oauth2/IdamSystemTokenGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacaseaccessapi/infrastructure/service/IdamServiceTest.java
https://tools.hmcts.net/jira/browse/DIAC-1243
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> DIAC-1243 caching tokens

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/iacaseaccessapi/testutils/FunctionalSpringContext.java, src/main/java/uk/gov/hmcts/reform/iacaseaccessapi/Application.java
See [DIAC-1418](https://tools.hmcts.net/jira/browse/DIAC-1418)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> DIAC-1418 removing hysterix as its unused
